import { Helmet } from "react-helmet-async";
import { useQuery } from "@tanstack/react-query";
import { apiClient } from "@/services/apiClient";
import { Card, CardHeader, CardTitle, CardContent, CardDescription } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Loader2, ExternalLink, Link } from "lucide-react";
import { format } from "date-fns";

export function GenerateLinkPage() {
  const { data: links, isLoading } = useQuery({
    queryKey: ['org', 'anonymous-links'],
    queryFn: async () => {
      const res = await apiClient.get('/org/anonymous-links/');
      return res.data;
    }
  });

  const formatDate = (dateString: string) => {
    if (!dateString) return "—";
    return format(new Date(dateString), "dd/MM/yyyy HH:mm");
  };

  return (
    <div className="space-y-6 w-full max-w-6xl mx-auto animate-in fade-in slide-in-from-bottom-4 duration-500 pb-12">
      <Helmet>
        <title>Generated Links</title>
      </Helmet>

      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 border-b border-border/40 pb-6">
        <div>
          <h1 className="text-3xl font-extrabold tracking-tight flex items-center gap-2">
            <Link className="h-8 w-8 text-primary" />
            Generated Links
          </h1>
          <p className="text-muted-foreground mt-1">
            History of all anonymous assessment links generated by you.
          </p>
        </div>
      </div>

      <Card className="border-primary/10 bg-background/50 backdrop-blur-sm">
        <CardHeader>
          <CardTitle>Generated Links History</CardTitle>
          <CardDescription>View previously generated links and their status.</CardDescription>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <div className="flex justify-center py-8">
              <Loader2 className="h-6 w-6 animate-spin text-primary" />
            </div>
          ) : links && links.length > 0 ? (
            <div className="rounded-md border overflow-hidden">
              <Table>
                <TableHeader className="bg-muted/50">
                  <TableRow>
                    <TableHead>Assessment</TableHead>
                    <TableHead>Generated On</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead>Used On</TableHead>
                    <TableHead>Link</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {links.map((link: any) => {
                    const fullUrl = `${window.location.origin}/assessment/${link.token}`;
                    return (
                      <TableRow key={link.token}>
                        <TableCell className="font-medium">{link.assessment_name}</TableCell>
                        <TableCell>{formatDate(link.created_at)}</TableCell>
                        <TableCell>
                          {link.used ? (
                            <Badge variant="secondary" className="bg-green-500/10 text-green-500 hover:bg-green-500/20">Used</Badge>
                          ) : new Date(link.expires_at) < new Date() ? (
                            <Badge variant="destructive" className="bg-red-500/10 text-red-500 hover:bg-red-500/20">Expired</Badge>
                          ) : (
                            <Badge variant="outline" className="bg-blue-500/10 text-blue-500 border-blue-500/20 hover:bg-blue-500/20">Active</Badge>
                          )}
                        </TableCell>
                        <TableCell>{formatDate(link.used_at)}</TableCell>
                        <TableCell className="flex items-center gap-2">
                          <a
                            href={fullUrl}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="inline-flex items-center gap-1 text-xs text-primary hover:underline font-mono"
                            title={fullUrl}
                          >
                            {link.token.substring(0, 8)}...
                            <ExternalLink className="h-3 w-3" />
                          </a>
                          {!link.used && new Date(link.expires_at) > new Date() && (
                            <button
                              onClick={async () => {
                                if(confirm("Are you sure you want to revoke this link?")) {
                                  try {
                                    await apiClient.delete(`/org/anonymous-links/${link.token}`);
                                    import("@tanstack/react-query").then(m => {
                                      const qc = new m.QueryClient();
                                      qc.invalidateQueries({ queryKey: ['org', 'anonymous-links'] });
                                      window.location.reload();
                                    });
                                  } catch (e) {
                                    console.error(e);
                                  }
                                }
                              }}
                              className="text-xs text-red-500 hover:underline ml-2"
                            >
                              Revoke
                            </button>
                          )}
                        </TableCell>
                      </TableRow>
                    );
                  })}
                </TableBody>
              </Table>
            </div>
          ) : (
            <div className="text-center py-8 text-muted-foreground border rounded-md border-dashed">
              No links have been generated yet.
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
