"""Add psychologist verification fields and VerificationRequest model

Revision ID: a835167e1b74
Revises: b2c3d4e5f6a7
Create Date: 2026-06-12 22:14:37.792511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a835167e1b74'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('assigned_psychologist_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'VERIFIED', 'REJECTED', 'EXPIRED', name='verificationrequeststatus'), nullable=False),
    sa.Column('assignment_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_psychologist_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_requests_assigned_psychologist_id'), 'verification_requests', ['assigned_psychologist_id'], unique=False)
    op.create_index(op.f('ix_verification_requests_session_id'), 'verification_requests', ['session_id'], unique=False)
    op.create_index(op.f('ix_verification_requests_status'), 'verification_requests', ['status'], unique=False)
    op.drop_index(op.f('ix_appointments_date'), table_name='appointments')
    op.drop_constraint(op.f('assessments_slug_key'), 'assessments', type_='unique')
    op.create_index(op.f('ix_assessments_id'), 'assessments', ['id'], unique=False)
    op.create_index(op.f('ix_assessments_slug'), 'assessments', ['slug'], unique=True)
    op.alter_column('audit_logs', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_audit_logs_admin_id'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_clinic_profiles_clinic_id'), 'clinic_profiles', ['clinic_id'], unique=False)
    op.drop_index(op.f('ix_password_resets_token'), table_name='password_resets')
    op.create_index(op.f('ix_password_resets_token'), 'password_resets', ['token'], unique=True)
    op.drop_constraint(op.f('fk_sessions_assigned_psychologist_id'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'users', ['assigned_psychologist_id'], ['id'])
    op.drop_constraint(op.f('user_verification_documents_user_id_document_type_key'), 'user_verification_documents', type_='unique')
    op.create_unique_constraint('uq_user_document_type', 'user_verification_documents', ['user_id', 'document_type'])
    op.add_column('users', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('experience_years', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('total_verifications_done', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_verifications_done')
    op.drop_column('users', 'experience_years')
    op.drop_column('users', 'rating')
    op.drop_constraint('uq_user_document_type', 'user_verification_documents', type_='unique')
    op.create_unique_constraint(op.f('user_verification_documents_user_id_document_type_key'), 'user_verification_documents', ['user_id', 'document_type'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_sessions_assigned_psychologist_id'), 'sessions', 'users', ['assigned_psychologist_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_password_resets_token'), table_name='password_resets')
    op.create_index(op.f('ix_password_resets_token'), 'password_resets', ['token'], unique=False)
    op.drop_index(op.f('ix_clinic_profiles_clinic_id'), table_name='clinic_profiles')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_admin_id'), 'audit_logs', ['user_id'], unique=False)
    op.alter_column('audit_logs', 'timestamp',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_assessments_slug'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_id'), table_name='assessments')
    op.create_unique_constraint(op.f('assessments_slug_key'), 'assessments', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_appointments_date'), 'appointments', ['appointment_date'], unique=False)
    op.drop_index(op.f('ix_verification_requests_status'), table_name='verification_requests')
    op.drop_index(op.f('ix_verification_requests_session_id'), table_name='verification_requests')
    op.drop_index(op.f('ix_verification_requests_assigned_psychologist_id'), table_name='verification_requests')
    op.drop_table('verification_requests')
    # ### end Alembic commands ###