"""Add AnonymousLink

Revision ID: cbfe8017bdf5
Revises: fdbfa151f000
Create Date: 2026-06-05 04:23:14.188331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbfe8017bdf5'
down_revision: Union[str, None] = 'fdbfa151f000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###