"""add_org_profile

Revision ID: f225654e1267
Revises: 8a9b1c2d3e4f
Create Date: 2026-06-05 03:51:43.475535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f225654e1267'
down_revision: Union[str, None] = '8a9b1c2d3e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_profiles',
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('org_name', sa.String(), nullable=True),
    sa.Column('tagline', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('support_phone', sa.String(), nullable=True),
    sa.Column('logo_path', sa.String(), nullable=True),
    sa.Column('cover_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('org_id')
    )
    
    # Manually add ENUM values
    op.execute("ALTER TYPE userrole ADD VALUE 'org_admin'")
    op.execute("ALTER TYPE userrole ADD VALUE 'org_staff'")
    op.execute("ALTER TYPE accounttype ADD VALUE 'organization'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('org_profiles')
    # Note: PostgreSQL does not support dropping ENUM values easily.
    # ### end Alembic commands ###