import { Helmet } from "react-helmet-async";
import { useQuery } from "@tanstack/react-query";
import { apiClient } from "@/services/apiClient";
import { Card, CardHeader, CardTitle, CardContent, CardDescription } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Loader2, ExternalLink, Link2, Link } from "lucide-react";
import { format } from "date-fns";

export function AdminGeneratedLinksPage() {
  const { data: links, isLoading } = useQuery({
    queryKey: ['admin', 'anonymous-links'],
    queryFn: async () => {
      const res = await apiClient.get('/admin/anonymous-links');
      return res.data;
    }
  });

  const formatDate = (dateString: string) => {
    if (!dateString) return "—";
    return format(new Date(dateString), "dd/MM/yyyy HH:mm");
  };

  const getStatus = (link: any) => {
    if (link.used) return "used";
    if (new Date(link.expires_at) < new Date()) return "expired";
    return "active";
  };

  return (
    <div className="space-y-6 w-full max-w-6xl mx-auto animate-in fade-in slide-in-from-bottom-4 duration-500 pb-12">
      <Helmet>
        <title>Generated Links  | CoreTAT - Psychological Intelligence</title>
      </Helmet>

      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 border-b border-border/40 pb-6">
        <div>
          <h1 className="text-3xl font-extrabold tracking-tight flex items-center gap-2">
            <Link className="h-8 w-8 text-primary" />
            Generated Links
          </h1>
          <p className="text-muted-foreground mt-1">
            Platform-wide history of all anonymous assessment links generated by any clinic or organization.
          </p>
        </div>
      </div>

      <Card className="border-primary/10 bg-background/50 backdrop-blur-sm">
        <CardHeader>
          <CardTitle>Platform-Wide Links History</CardTitle>
          <CardDescription>All previously generated assessment links, sorted by most recent. Includes creator details and usage status.</CardDescription>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <div className="flex justify-center py-12">
              <Loader2 className="h-6 w-6 animate-spin text-primary" />
            </div>
          ) : links && links.length > 0 ? (
            <div className="rounded-md border overflow-hidden">
              <Table>
                <TableHeader className="bg-muted/50">
                  <TableRow>
                    <TableHead>Organization / Clinic</TableHead>
                    <TableHead>Created By</TableHead>
                    <TableHead>Assessment</TableHead>
                    <TableHead>Generated On</TableHead>
                    <TableHead>Expires</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead>Used On</TableHead>
                    <TableHead>Link Token</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {links.map((link: any) => {
                    const fullUrl = `${window.location.origin}/assessment/${link.token}`;
                    const status = getStatus(link);
                    return (
                      <TableRow key={link.token} className="hover:bg-muted/30 transition-colors">
                        <TableCell>
                          <div className="flex flex-col">
                            <span className="font-medium text-sm">{link.creator_clinic}</span>
                          </div>
                        </TableCell>
                        <TableCell>
                          <div className="flex flex-col">
                            <span className="font-medium text-sm">{link.creator_name}</span>
                            <span className="text-xs text-muted-foreground capitalize">{link.creator_role?.replace("_", " ")}</span>
                          </div>
                        </TableCell>
                        <TableCell className="font-medium text-sm">{link.assessment_name}</TableCell>
                        <TableCell className="text-sm text-muted-foreground">{formatDate(link.created_at)}</TableCell>
                        <TableCell className="text-sm text-muted-foreground">
                          {link.expires_at ? (
                            <span className={new Date(link.expires_at) < new Date() ? "text-red-500" : ""}>
                              {formatDate(link.expires_at)}
                            </span>
                          ) : "—"}
                        </TableCell>
                        <TableCell>
                          {status === "used" ? (
                            <Badge className="bg-green-500/10 text-green-600 dark:text-green-400 border-green-500/20 hover:bg-green-500/20">Used</Badge>
                          ) : status === "expired" ? (
                            <Badge className="bg-red-500/10 text-red-600 dark:text-red-400 border-red-500/20 hover:bg-red-500/20">Expired</Badge>
                          ) : (
                            <Badge className="bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/20 hover:bg-blue-500/20">Active</Badge>
                          )}
                        </TableCell>
                        <TableCell className="text-sm text-muted-foreground">{formatDate(link.used_at)}</TableCell>
                        <TableCell>
                          <a
                            href={fullUrl}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="inline-flex items-center gap-1 text-xs text-primary hover:underline font-mono"
                            title={fullUrl}
                          >
                            {link.token.substring(0, 8)}...
                            <ExternalLink className="h-3 w-3" />
                          </a>
                        </TableCell>
                      </TableRow>
                    );
                  })}
                </TableBody>
              </Table>
            </div>
          ) : (
            <div className="text-center py-12 text-muted-foreground border rounded-xl border-dashed">
              <Link2 className="h-10 w-10 mx-auto mb-3 opacity-30" />
              <p className="font-medium">No links have been generated yet</p>
              <p className="text-xs mt-1">Once org staff or clinic staff generate links, they will appear here.</p>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
