"""add consent to anonymous links

Revision ID: b2c3d4e5f6a8
Revises: a1b2c3d4e5f6
Create Date: 2026-06-13 03:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2c3d4e5f6a8'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    insp = sa.inspect(conn)
    columns = [col['name'] for col in insp.get_columns('anonymous_links')]
    
    if 'consent_given' not in columns:
        op.add_column('anonymous_links', sa.Column('consent_given', sa.Boolean(), nullable=False, server_default='false'))
    if 'consent_timestamp' not in columns:
        op.add_column('anonymous_links', sa.Column('consent_timestamp', sa.DateTime(timezone=True), nullable=True))
    if 'consent_ip_address' not in columns:
        op.add_column('anonymous_links', sa.Column('consent_ip_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anonymous_links', 'consent_ip_address')
    op.drop_column('anonymous_links', 'consent_timestamp')
    op.drop_column('anonymous_links', 'consent_given')
    # ### end Alembic commands ###
